import Head from 'next/head'

const Layout = ({ children }) => {
    return (
        <main>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Syncopate:wght@400;700&display=swap" rel="stylesheet" />            
            </Head>
            {children}
        </main>
    )
}
export default Layout